"LR": 0.0005
"NUM_ENVS": 256
"NUM_STEPS": 128
"TOTAL_TIMESTEPS": 2e8
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 16
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"GRU_HIDDEN_DIM": 256
"FC_DIM_SIZE": 256
"ENV_NAME": "clean_up"
"REW_SHAPING_HORIZON": 5e7
"ENV_KWARGS":
  "num_agents": 2
  "num_inner_steps": 1000
  "shared_rewards": False
  "cnn": True
  "jit": True
  "svo": True
  "svo_target_agents": [0, 1]
  "svo_w": 0.5
  "svo_ideal_angle_degrees": 90

"ANNEAL_LR": False
"SEED": 30
"NUM_SEEDS": 1
"TUNE": False

"REWARD": "individual"
"GIF_NUM_FRAMES": 250
"PARAMETER_SHARING": True
"TOM_AUX_HIDDEN": False
"TOM_STOP_GRAD_PARTNER": True

"ENTITY": ""
"PROJECT": "svo_socialjax"
"WANDB_MODE": "online"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD
  - SVO
  - RNN
